INTEGER, PLUS, MINUS, MUL, DIV, EOF, RPAREN, LPAREN, LESS, GREATER, EQUAL, NOT_EQUAL, LESS_EQ, GREATER_EQ  = (
    'INTEGER', 'PLUS', 'MINUS', 'MUL', 'DIV', 'EOF', 'RPAREN', 'LPAREN', 'LESS', 'GREATER', 'EQUAL', 'NOT_EQUAL', 'LESS_EQ', 'GREATER_EQ'
)

ID = 'ID'
TYPE = 'TYPE'
HASH = 'HASH'
RBRACKET = 'RBRACKET'
LBRACKET = 'LBRACKET'
DOT = 'DOT'
SEMICOLON = 'SEMICOLON'
ASSIGN = 'ASSIGN'
COMMA = 'COMMA'